# Generated by Django 5.2.5 on 2025-08-24 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('I', 'Income'), ('E', 'Expense')], default='I', max_length=100),
        ),
        migrations.AddField(
            model_name='transactions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='transactions',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='transactions',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
