# Generated by Django 5.2.5 on 2025-08-26 05:25

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='lastName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='seed',
            field=models.CharField(default=App.models.generate_seed, max_length=20),
        ),
    ]
