# Generated by Django 5.2.5 on 2025-08-26 06:24

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_users_lastname_users_name_alter_users_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='seed',
            field=models.CharField(default=App.models.generate_seed, max_length=20, unique=True),
        ),
    ]
