# Generated by Django 5.2.5 on 2025-08-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_users_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='userSeed',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
